### ISSUE TITLE
remove loading spinner on empty timelines

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-tool#104]
**Describe the bug**
If a timeline is empty, the loading spinner which appears on visiting someones user details is loading forever.

**To Reproduce**
1. Go to a random tracemap in the tool
2. Click on a user
3. Change timeline settings to just display this users tweets (no retweets)
4. Leave this users details
5. Click on other users until one has just retweeted for the last 200 tweets/retweets we give to the frontend
6. The loading spinner is not finishing because it awaits rendered signals from tweets which are not there

**Expected behavior**
- [ ] The loading spinner should not appear if no content is there.
- [ ] A card, which tells the user that there is not tweet for this settings should appear instead.

**Screenshots**
![screenshot from 2018-10-13 16-48-43](https://user-images.githubusercontent.com/9152141/46906695-e7793080-cf07-11e8-85a9-eb7a71363ded.png)

**Comment by jonathanschlue** [comment]
Merged by #106
