### ISSUE TITLE
Audit security warnings

### ISSUE THREAD

**Issue by jonathanschlue** [tracemap/tracemap-tool#115]
## Description

Npm complains about security issues:

```sh
audited 11623 packages in 9.078s                                                                                                                               │drwxr-xr-x  2 jonathan users 4,0K 18. Okt 16:23 monitoring
found 19 vulnerabilities (9 low, 4 moderate, 6 high)                                                                                                           │drwxr-xr-x  2 root     root  4,0K 23. Okt 17:27 __pycache__
  run `npm audit fix` to fix them, or `npm audit` for details 
```

![bildschirmfoto vom 2018-10-29 13-04-18](https://user-images.githubusercontent.com/15818147/47648741-cd2f8b80-db72-11e8-9816-7ba11783ee44.png)

## Progress checklist

- [ ] run npm audit
- [ ] check warnings

## Testing hints

- run `npm install` and check if there are still warnings.

**Comment by jonathanschlue** [comment]
`npm audit` suggests the following pinned versions:

- [ ] `npm install --save-dev karma@3.1.1 ` 
- [ ] `npm install --save-dev protractor@5.4.1 `
- [ ] `npm install --save-dev @angular/cli@7.0.3`

**Comment by jonathanschlue** [comment]
Only updated protractor and ibm plex, as other changes are breaking.

**Comment by Eik-S** [comment]
The tool is running as before. :+1: 
The npm audit warnings are just related to dev dependencies and therefore not urgent. :+1:
