### ISSUE TITLE
100 Retweets Warning

### ISSUE THREAD

**Issue by allegra1** [tracemap/tracemap-tool#137]
Please correct writing: "This tweet has more than 100 retweets.
At the moment TraceMap is restricted by Twitter to only display the latest 100 retweets."

I would also like to take out completely the header "important information"

**Comment by Eik-S** [comment]
could you please tell me the new version?

**Comment by allegra1** [comment]
Its just the groß und klein schreibung that is wrong. I corrected it in the description
