### ISSUE TITLE
Source tweet and thumbnails missing in firefox

### ISSUE THREAD

**Issue by jonathanschlue** [tracemap/tracemap-tool#95]
I am experiencing missing source tweet and thumbnails in the left panel in my overconfigured firefox:

![Bildschirmfoto vom 2018-10-11 21-48-22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e91cde7c1910001264383c/125516c66e82c728ace21e0d46ca9d96279180a186fbb245ab49ffd43f492a337b54f2733dd4b365ee133b535e424aa45c5a5d56e0ebc969f9ec6923ce4e01ffd43f0d7ccf6f16fdead71eee00be208b4981e4b98f19c2eb2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee24457ac143562e2733e7c55d9.png)

Please check if you can reproduce this error @brunopace ,  @Eik-S. If it is not related to my specific settings but to firefox, then we should adress fixing this.

**Comment by Eik-S** [comment]
Please specify your firefox version and the version of the tool you are using (localhost or tool.tracemap.info)

**Comment by Eik-S** [comment]
The Error seems to be related to jonathan's browser settings and addons. If someone else with default browser settings is experiencing the error. Please comment here providing the following:
- screenshot (especially from the browser console/network messages
- browser type and version number

**Comment by jonathanschlue** [comment]
Closed because related to personal, overly paranoid firefox browser settings.
