### ISSUE TITLE
remove loading spinner for the wordcloud

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-tool#97]
**Describe the bug**
The loading spinner is always appearing if you click on a wordcloud word.
This is annoying and not looking too nice.

**To Reproduce**
1. Go to the tool for a random tweet
2. Click on a user
3. Select one of the smallest words in the wordcloud

**Expected behavior**
- The loading spinner should just appear if timeline is rendered for the first time (this should fix the spinner problems).

**Comment by jonathanschlue** [comment]
Merged in #101
