### ISSUE TITLE
wordcloud.component.ts console error

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-tool#99]
**Describe the bug**
if clicking on a user, the console throws an error appearing in wordcloud.component.ts

**To Reproduce**
1. Go to the tool
2. Click on a user with open web console
3. Errors appear in console

**Screenshots**
![screenshot from 2018-10-13 14-52-10](https://user-images.githubusercontent.com/9152141/46905697-a0833f00-cef7-11e8-9585-5d058ea820f8.png)

**Comment by jonathanschlue** [comment]
Errors are gone. Merged in #100
